"""Make confirmed field on Account model non-nullable

Revision ID: 75e8b887383b
Revises: b53d466f5c9f
Create Date: 2020-01-02 16:43:23.945520

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '75e8b887383b'
down_revision = 'b53d466f5c9f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('accounts', schema=None) as batch_op:
        batch_op.alter_column('confirmed',
               existing_type=sa.BOOLEAN(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('accounts', schema=None) as batch_op:
        batch_op.alter_column('confirmed',
               existing_type=sa.BOOLEAN(),
               nullable=True)

    # ### end Alembic commands ###
