"""Make comment option on blog non-nullable

Revision ID: 9616ca3c6cfb
Revises: dca1edd72ddd
Create Date: 2020-09-03 17:09:09.413781

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9616ca3c6cfb'
down_revision = 'dca1edd72ddd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('blogs', schema=None) as batch_op:
        batch_op.alter_column('comment',
               existing_type=sa.BOOLEAN(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('blogs', schema=None) as batch_op:
        batch_op.alter_column('comment',
               existing_type=sa.BOOLEAN(),
               nullable=True)

    # ### end Alembic commands ###
