"""Add confirmed field to Account model

Revision ID: b53d466f5c9f
Revises: da2a7f33f56c
Create Date: 2020-01-02 10:47:36.757828

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b53d466f5c9f'
down_revision = 'da2a7f33f56c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('accounts', sa.Column('confirmed', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('accounts', 'confirmed')
    # ### end Alembic commands ###
