"""Add published field to Blog model

Revision ID: d0df9fadc5b3
Revises: a0d50c3848b9
Create Date: 2020-01-26 08:35:21.805158

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd0df9fadc5b3'
down_revision = 'a0d50c3848b9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('blogs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('published', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('blogs', schema=None) as batch_op:
        batch_op.drop_column('published')

    # ### end Alembic commands ###
