"""Add option to allow comments on blog

Revision ID: dca1edd72ddd
Revises: 6ab2d44e6f26
Create Date: 2020-09-03 16:42:12.372167

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dca1edd72ddd'
down_revision = '6ab2d44e6f26'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('blogs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('comment', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('blogs', schema=None) as batch_op:
        batch_op.drop_column('comment')

    # ### end Alembic commands ###
