"""Add fields to Account model

Revision ID: f09c0905c684
Revises: 75e8b887383b
Create Date: 2020-01-03 14:55:28.325032

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f09c0905c684'
down_revision = '75e8b887383b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('accounts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('about', sa.String(length=300), nullable=True))
        batch_op.add_column(sa.Column('seen_at', sa.DateTime(timezone=True), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('accounts', schema=None) as batch_op:
        batch_op.drop_column('seen_at')
        batch_op.drop_column('about')

    # ### end Alembic commands ###
